# Generated by Django 5.0.6 on 2024-06-21 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_news_gender_choices'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='gender_choices',
        ),
    ]
